dataset:
  name: "co3d_duster"
  train_bs: 1
  num_viewpoints: 3
  num_ref: 2
  target_idx: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - "./data/fashion_meta.json"
  # Margin of frame indexes between ref and tgt images
  sample_margin: 30  

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'no'
  enable_xformers_memory_efficient_attention: true
  gradient_checkpointing: False
  max_train_steps: 500000
  max_grad_norm: 1.0
  
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 2000

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

vae_model_path: /mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/checkpoints/complete/sd-vae-ft-mse
image_encoder_path: 'laion/CLIP-ViT-H-14-laion2B-s32B-b79K'
model_path: /mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/checkpoints/complete
model_depth_path: /mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/checkpoints/complete
model_pointmap_path: /mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/checkpoints/complete
model_normal_path: /mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/checkpoints/complete
model_path_scratch: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/original_two'

feature_fusion_type: "attention_full_sharing"
kaist: false

inference: false
debugging: false
local_data: false
multi_dataset: false
co3d_only: false
step_control: false

interpolate_only: false

optimizer_load: true
train_from_scratch: false
train_from_complete: true

img_weight: 1.0
weight_1: 2.7
weight_2: 1.0
weight_3: 0.7

train_geo_only: false
train_geo_2_only: false
geo_second: true
geo_third: false
use_geo_ref_unet: true
use_geo_2_ref_unet: false
use_warped_geo_cond_at_geo: false
geo_setting: "pointmap"
geo_setting_2: "depth"
depth_min: 0.05
depth_max: 0.8897

use_mesh: true
downsample: true
use_normal: true
use_normal_mask: true
downsample_by: 4

use_depthmap: true
use_conf: false
use_plucker: false
use_warped_img_cond: false
gt_cor_reg: false
use_gt_cor: false
pure_gt: false
gt_mask_threshold: 0.004
conditioning_pointmap_norm: true
embed_pointmap_norm: true

switcher: false
multitask_mode: "loc" 
multitask_weighting: false
image_weight: 0.9
ref_net_expand: false
both_loss: false
uncertainty_loss: false
multitask: false

point_masking: false
masking_percent: 0.9

find_unused_params: false
use_lora: false
weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
pose_guider_pretrain: False

seed: 12580
resume_from_checkpoint: "./exp_output/interpolated_realestate_250228_110030"
checkpointing_steps: 1300
save_model_epoch_interval: 5
exp_name: 'interpolated_realestate'
output_dir: './exp_output' 