dataset:
  name: "realestate"
  train_bs: 2
  num_viewpoints: 3
  num_ref: 2
  target_idx: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - "./data/fashion_meta.json"
  # Margin of frame indexes between ref and tgt images
  sample_margin: 30  

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False
  max_train_steps: 500000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 2000

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

# base_model_path: './pretrained_weights/sd-image-variations-diffusers'
vae_model_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/sd-vae-ft-mse'
image_encoder_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/image_encoder'
controlnet_openpose_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/multi1/pose_guider.pth'
model_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/multi1'
# denoising_unet_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/denoising_unet'
# reference_unet_path: '/mnt/image-net-full/j1nhwa.kim/interns/minseop.kwak/multiview-gen/genwarp/checkpoints/reference_unet'

feature_fusion_type: "attention_full_sharing"
find_unused_params: true
use_lora: true

weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
pose_guider_pretrain: False

seed: 12580
resume_from_checkpoint: ''
checkpointing_steps: 2000
save_model_epoch_interval: 5
exp_name: 'realestate_lora'
output_dir: './exp_output' 

compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,1,2,3,4,5,6,7
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 8
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29400